name: Test and compile Yamlpath
on: [push]
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: build
        uses: cedrickring/golang-action@1.4.1
        env:
          GO111MODULE: on
